version: "3.9"
services:
  coder:
    build:
      context: .
      dockerfile: etc/docker/Dockerfile
    ports:
      - 127.0.0.1:8080:8080
      - 3000:3000
    restart: always
    volumes:
      - ${PWD}/.config:/home/coder/.config
      - ${PWD}/project:/home/coder/project
    environment:
      - DOCKER_USER=${USER}
